# Generated by Django 5.1 on 2025-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('countrycity', models.CharField(blank=True, max_length=100)),
                ('countrypostal', models.CharField(blank=True, max_length=100)),
                ('countrystreet', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
