# Generated by Django 5.1 on 2025-02-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='address',
            name='countrycity',
        ),
        migrations.RemoveField(
            model_name='address',
            name='countrystreet',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
    ]
