# Generated by Django 5.1 on 2024-12-01 09:16

import company.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('employer_status', models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer (CEO)'), ('HR', 'Human Resources (HR)'), ('Manager', 'Manager'), ('Recruiter', 'Recruiter'), ('Staff', 'Staff')], max_length=50)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='office-building.png', null=True, upload_to=company.models.company_avatar_upload_path, validators=[company.models.validate_avatar])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('dateFounded', models.DateTimeField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bir_file', models.FileField(blank=True, null=True, upload_to=company.models.company_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), company.models.validate_file_size])),
                ('dti_file', models.FileField(blank=True, null=True, upload_to=company.models.company_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), company.models.validate_file_size])),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='address.address')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='industries', to='industry.industry')),
            ],
        ),
    ]
