# Generated by Django 5.1 on 2024-11-23 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='office-building.png', upload_to='company')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bir_file', models.FileField(blank=True, null=True, upload_to='company-file')),
                ('dti_file', models.FileField(blank=True, null=True, upload_to='company-file')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='address.address')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='industries', to='industry.industry')),
            ],
        ),
    ]
