# Generated by Django 5.1 on 2025-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_status',
            field=models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer (CEO)'), ('HR', 'Human Resources (HR)'), ('Manager', 'Manager'), ('Recruiter', 'Recruiter'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
    ]
