# Generated by Django 5.1 on 2024-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_status',
            field=models.CharField(blank=True, choices=[('CEO', 'Chief Executive Officer (CEO)'), ('HR', 'Human Resources (HR)'), ('Manager', 'Manager'), ('Recruiter', 'Recruiter'), ('Staff', 'Staff')], max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
