# Generated by Django 5.1 on 2024-11-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_employer_employer_status_employer_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='linkedin',
        ),
    ]
