# Generated by Django 5.1 on 2024-11-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('company', '0006_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='address.address'),
        ),
    ]
