# Generated by Django 5.1 on 2024-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_employer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='dateCreated',
            new_name='dateFounded',
        ),
    ]
