# Generated by Django 5.1 on 2024-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_employee_count_company_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
