# Generated by Django 5.1 on 2024-11-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='instagram_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='linkedin_url',
            new_name='twitter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter_url',
        ),
    ]
