# Generated by Django 5.1 on 2024-11-29 08:16

import company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_rename_facebook_url_company_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bir_file',
            field=models.FileField(blank=True, null=True, upload_to='company-file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), company.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='dti_file',
            field=models.FileField(blank=True, null=True, upload_to='company-file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), company.models.validate_file_size]),
        ),
    ]
