# Generated by Django 5.1 on 2024-11-29 08:37

import company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_bir_file_alter_company_dti_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bir_file',
            field=models.FileField(blank=True, null=True, upload_to=company.models.company_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), company.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='company',
            name='dti_file',
            field=models.FileField(blank=True, null=True, upload_to=company.models.company_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), company.models.validate_file_size]),
        ),
    ]
