# Generated by Django 5.1 on 2024-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expt_salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='expt_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
