# Generated by Django 5.1 on 2025-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expt_salary_fixed',
            field=models.PositiveIntegerField(blank=True, help_text='Enter fixed salary if selected.', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='salary_display_type',
            field=models.CharField(choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='range', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expt_salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='Enter maximum salary for range.', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expt_salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='Enter minimum salary for range.', null=True),
        ),
    ]
