# Generated by Django 5.1 on 2024-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_expt_salary_max_resume_expt_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='employment_job_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship/OJT', 'Internship/OJT')], max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='location_job_type',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
