# Generated by Django 5.1 on 2024-11-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('resume', '0004_resume_employment_job_type_resume_location_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='industry.industry'),
        ),
    ]
