# Generated by Django 5.1 on 2025-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expt_salary_mode',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20),
        ),
    ]
