# Generated by Django 5.1 on 2024-11-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='status',
        ),
    ]
