# Generated by Django 5.1 on 2025-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_expt_salary_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='expt_salary_mode',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
