# Generated by Django 5.1 on 2025-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_expt_salary_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='salary_display_type',
            field=models.CharField(choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='hidden', max_length=10),
        ),
    ]
