# Generated by Django 5.1 on 2024-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_certification_name_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
