# Generated by Django 5.1 on 2025-03-13 20:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interview Scheduled'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', max_length=20)),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('APPLICANT', 'Applicant Feedback'), ('INTERVIEWER', 'Interviewer Feedback')], max_length=20)),
                ('content', models.TextField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_type', models.CharField(blank=True, choices=[('VIRTUAL', 'Virtual'), ('ONSITE', 'Onsite'), ('PHONE', 'Phone'), ('GROUP', 'Group'), ('PANEL', 'Panel'), ('OTHER', 'Other')], default='VIRTUAL', max_length=50, null=True)),
                ('interviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('salary_display_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='fixed', max_length=10, null=True)),
                ('currency', models.CharField(choices=[('USD', '$'), ('CAD', 'CA$'), ('EUR', '€'), ('AED', 'AED'), ('AFN', 'Af'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('ARS', 'AR$'), ('AUD', 'AU$'), ('AZN', 'man.'), ('BAM', 'KM'), ('BDT', 'Tk'), ('BGN', 'BGN'), ('BHD', 'BD'), ('BIF', 'FBu'), ('BND', 'BN$'), ('BOB', 'Bs'), ('BRL', 'R$'), ('BWP', 'BWP'), ('BYN', 'Br'), ('BZD', 'BZ$'), ('CDF', 'CDF'), ('CHF', 'CHF'), ('CLP', 'CL$'), ('CNY', 'CN¥'), ('COP', 'CO$'), ('CRC', '₡'), ('CVE', 'CV$'), ('CZK', 'Kč'), ('DJF', 'Fdj'), ('DKK', 'Dkr'), ('DOP', 'RD$'), ('DZD', 'DA'), ('EEK', 'Ekr'), ('EGP', 'EGP'), ('ERN', 'Nfk'), ('ETB', 'Br'), ('GBP', '£'), ('GEL', 'GEL'), ('GHS', 'GH₵'), ('GNF', 'FG'), ('GTQ', 'GTQ'), ('HKD', 'HK$'), ('HNL', 'HNL'), ('HRK', 'kn'), ('HUF', 'Ft'), ('IDR', 'Rp'), ('ILS', '₪'), ('INR', 'Rs'), ('IQD', 'IQD'), ('IRR', 'IRR'), ('ISK', 'Ikr'), ('JMD', 'J$'), ('JOD', 'JD'), ('JPY', '¥'), ('KES', 'Ksh'), ('KHR', 'KHR'), ('KMF', 'CF'), ('KRW', '₩'), ('KWD', 'KD'), ('KZT', 'KZT'), ('LBP', 'L.L.'), ('LKR', 'SLRs'), ('LTL', 'Lt'), ('LVL', 'Ls'), ('LYD', 'LD'), ('MAD', 'MAD'), ('MDL', 'MDL'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('MMK', 'MMK'), ('MOP', 'MOP$'), ('MUR', 'MURs'), ('MXN', 'MX$'), ('MYR', 'RM'), ('MZN', 'MTn'), ('NAD', 'N$'), ('NGN', '₦'), ('NIO', 'C$'), ('NOK', 'Nkr'), ('NPR', 'NPRs'), ('NZD', 'NZ$'), ('OMR', 'OMR'), ('PAB', 'B/.'), ('PEN', 'S/.'), ('PHP', '₱'), ('PKR', 'PKRs'), ('PLN', 'zł'), ('PYG', '₲'), ('QAR', 'QR'), ('RON', 'RON'), ('RSD', 'din.'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SAR', 'SR'), ('SDG', 'SDG'), ('SEK', 'Skr'), ('SGD', 'S$'), ('SOS', 'Ssh'), ('SYP', 'SY£'), ('THB', '฿'), ('TND', 'DT'), ('TOP', 'T$'), ('TRY', 'TL'), ('TTD', 'TT$'), ('TWD', 'NT$'), ('TZS', 'TSh'), ('UAH', '₴'), ('UGX', 'USh'), ('UYU', '$U'), ('UZS', 'UZS'), ('VEF', 'Bs.F.'), ('VND', '₫'), ('XAF', 'FCFA'), ('XOF', 'CFA'), ('YER', 'YR'), ('ZAR', 'R'), ('ZMK', 'ZK'), ('ZWL', 'ZWL$')], default='PHP', max_length=3)),
                ('salary_fixed', models.PositiveIntegerField(blank=True, help_text='Enter fixed salary if selected.', null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Enter minimum salary for range.', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Enter maximum salary for range.', null=True)),
                ('salary_mode', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('use_company_location', models.BooleanField(default=False)),
                ('employment_job_type', models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship/OJT', 'Internship/OJT')], max_length=20)),
                ('location_job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('posted_date_time', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bene_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('doctorate', 'Doctorate (Ph.D.)'), ('vocational', 'Vocational/Technical'), ('other', 'Other')], max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('fixed', 'Fixed'), ('range', 'Range')], default='fixed', max_length=10)),
                ('exp_name', models.CharField(blank=True, max_length=300)),
                ('exp_years', models.IntegerField(blank=True, null=True)),
                ('min_exp_years', models.IntegerField(blank=True, null=True)),
                ('max_exp_years', models.IntegerField(blank=True, null=True)),
                ('exp_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_IdealCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('url_location', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('fair_event_held', models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('application_starts', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/di2hrzuyq/image/upload/v1733062519/luabhrtwak2aeu98sq71.jpg', max_length=255, verbose_name='images')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobFairRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_display_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='fixed', max_length=10, null=True)),
                ('currency', models.CharField(choices=[('USD', '$'), ('CAD', 'CA$'), ('EUR', '€'), ('AED', 'AED'), ('AFN', 'Af'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('ARS', 'AR$'), ('AUD', 'AU$'), ('AZN', 'man.'), ('BAM', 'KM'), ('BDT', 'Tk'), ('BGN', 'BGN'), ('BHD', 'BD'), ('BIF', 'FBu'), ('BND', 'BN$'), ('BOB', 'Bs'), ('BRL', 'R$'), ('BWP', 'BWP'), ('BYN', 'Br'), ('BZD', 'BZ$'), ('CDF', 'CDF'), ('CHF', 'CHF'), ('CLP', 'CL$'), ('CNY', 'CN¥'), ('COP', 'CO$'), ('CRC', '₡'), ('CVE', 'CV$'), ('CZK', 'Kč'), ('DJF', 'Fdj'), ('DKK', 'Dkr'), ('DOP', 'RD$'), ('DZD', 'DA'), ('EEK', 'Ekr'), ('EGP', 'EGP'), ('ERN', 'Nfk'), ('ETB', 'Br'), ('GBP', '£'), ('GEL', 'GEL'), ('GHS', 'GH₵'), ('GNF', 'FG'), ('GTQ', 'GTQ'), ('HKD', 'HK$'), ('HNL', 'HNL'), ('HRK', 'kn'), ('HUF', 'Ft'), ('IDR', 'Rp'), ('ILS', '₪'), ('INR', 'Rs'), ('IQD', 'IQD'), ('IRR', 'IRR'), ('ISK', 'Ikr'), ('JMD', 'J$'), ('JOD', 'JD'), ('JPY', '¥'), ('KES', 'Ksh'), ('KHR', 'KHR'), ('KMF', 'CF'), ('KRW', '₩'), ('KWD', 'KD'), ('KZT', 'KZT'), ('LBP', 'L.L.'), ('LKR', 'SLRs'), ('LTL', 'Lt'), ('LVL', 'Ls'), ('LYD', 'LD'), ('MAD', 'MAD'), ('MDL', 'MDL'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('MMK', 'MMK'), ('MOP', 'MOP$'), ('MUR', 'MURs'), ('MXN', 'MX$'), ('MYR', 'RM'), ('MZN', 'MTn'), ('NAD', 'N$'), ('NGN', '₦'), ('NIO', 'C$'), ('NOK', 'Nkr'), ('NPR', 'NPRs'), ('NZD', 'NZ$'), ('OMR', 'OMR'), ('PAB', 'B/.'), ('PEN', 'S/.'), ('PHP', '₱'), ('PKR', 'PKRs'), ('PLN', 'zł'), ('PYG', '₲'), ('QAR', 'QR'), ('RON', 'RON'), ('RSD', 'din.'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SAR', 'SR'), ('SDG', 'SDG'), ('SEK', 'Skr'), ('SGD', 'S$'), ('SOS', 'Ssh'), ('SYP', 'SY£'), ('THB', '฿'), ('TND', 'DT'), ('TOP', 'T$'), ('TRY', 'TL'), ('TTD', 'TT$'), ('TWD', 'NT$'), ('TZS', 'TSh'), ('UAH', '₴'), ('UGX', 'USh'), ('UYU', '$U'), ('UZS', 'UZS'), ('VEF', 'Bs.F.'), ('VND', '₫'), ('XAF', 'FCFA'), ('XOF', 'CFA'), ('YER', 'YR'), ('ZAR', 'R'), ('ZMK', 'ZK'), ('ZWL', 'ZWL$')], default='PHP', max_length=3)),
                ('salary_fixed', models.PositiveIntegerField(blank=True, help_text='Enter a fixed salary.', null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Enter minimum salary for range.', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Enter maximum salary for range.', null=True)),
                ('salary_mode', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
