# Generated by Django 5.1 on 2024-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='use_company_location',
            field=models.BooleanField(default=False),
        ),
    ]
