# Generated by Django 5.1 on 2025-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('CAD', 'CA$'), ('EUR', '€'), ('AED', 'AED'), ('AFN', 'Af'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('ARS', 'AR$'), ('AUD', 'AU$'), ('AZN', 'man.'), ('BAM', 'KM'), ('BDT', 'Tk'), ('BGN', 'BGN'), ('BHD', 'BD'), ('BIF', 'FBu'), ('BND', 'BN$'), ('BOB', 'Bs'), ('BRL', 'R$'), ('BWP', 'BWP'), ('BYN', 'Br'), ('BZD', 'BZ$'), ('CDF', 'CDF'), ('CHF', 'CHF'), ('CLP', 'CL$'), ('CNY', 'CN¥'), ('COP', 'CO$'), ('CRC', '₡'), ('CVE', 'CV$'), ('CZK', 'Kč'), ('DJF', 'Fdj'), ('DKK', 'Dkr'), ('DOP', 'RD$'), ('DZD', 'DA'), ('EEK', 'Ekr'), ('EGP', 'EGP'), ('ERN', 'Nfk'), ('ETB', 'Br'), ('GBP', '£'), ('GEL', 'GEL'), ('GHS', 'GH₵'), ('GNF', 'FG'), ('GTQ', 'GTQ'), ('HKD', 'HK$'), ('HNL', 'HNL'), ('HRK', 'kn'), ('HUF', 'Ft'), ('IDR', 'Rp'), ('ILS', '₪'), ('INR', 'Rs'), ('IQD', 'IQD'), ('IRR', 'IRR'), ('ISK', 'Ikr'), ('JMD', 'J$'), ('JOD', 'JD'), ('JPY', '¥'), ('KES', 'Ksh'), ('KHR', 'KHR'), ('KMF', 'CF'), ('KRW', '₩'), ('KWD', 'KD'), ('KZT', 'KZT'), ('LBP', 'L.L.'), ('LKR', 'SLRs'), ('LTL', 'Lt'), ('LVL', 'Ls'), ('LYD', 'LD'), ('MAD', 'MAD'), ('MDL', 'MDL'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('MMK', 'MMK'), ('MOP', 'MOP$'), ('MUR', 'MURs'), ('MXN', 'MX$'), ('MYR', 'RM'), ('MZN', 'MTn'), ('NAD', 'N$'), ('NGN', '₦'), ('NIO', 'C$'), ('NOK', 'Nkr'), ('NPR', 'NPRs'), ('NZD', 'NZ$'), ('OMR', 'OMR'), ('PAB', 'B/.'), ('PEN', 'S/.'), ('PHP', '₱'), ('PKR', 'PKRs'), ('PLN', 'zł'), ('PYG', '₲'), ('QAR', 'QR'), ('RON', 'RON'), ('RSD', 'din.'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SAR', 'SR'), ('SDG', 'SDG'), ('SEK', 'Skr'), ('SGD', 'S$'), ('SOS', 'Ssh'), ('SYP', 'SY£'), ('THB', '฿'), ('TND', 'DT'), ('TOP', 'T$'), ('TRY', 'TL'), ('TTD', 'TT$'), ('TWD', 'NT$'), ('TZS', 'TSh'), ('UAH', '₴'), ('UGX', 'USh'), ('UYU', '$U'), ('UZS', 'UZS'), ('VEF', 'Bs.F.'), ('VND', '₫'), ('XAF', 'FCFA'), ('XOF', 'CFA'), ('YER', 'YR'), ('ZAR', 'R'), ('ZMK', 'ZK'), ('ZWL', 'ZWL$')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_display_type',
            field=models.CharField(choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_fixed',
            field=models.PositiveIntegerField(blank=True, help_text='Enter fixed salary if selected.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='Enter maximum salary for range.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='Enter minimum salary for range.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
