# Generated by Django 5.1 on 2025-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_currency_job_salary_display_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ideal_candidate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
