# Generated by Django 5.1 on 2024-11-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_posted_date_remove_job_posted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10),
        ),
    ]
