# Generated by Django 5.1 on 2024-12-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
        ('job', '0004_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobfair', to='address.address'),
        ),
    ]
