# Generated by Django 5.1 on 2025-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_ideal_candidate_alter_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_display_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Salary'), ('range', 'Salary Range'), ('hidden', 'Do not display')], default='fixed', max_length=10, null=True),
        ),
    ]
