# Generated by Django 5.1 on 2024-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_salary_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='location_job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='employment_job_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship/Ojt', 'Internship/Ojt')], max_length=20),
        ),
    ]
