# Generated by Django 5.1 on 2024-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_job_type_job_location_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_job_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship/OJT', 'Internship/OJT')], max_length=20),
        ),
    ]
