# Generated by Django 5.1 on 2024-11-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_employment_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='use_company_location',
            field=models.BooleanField(default=True),
        ),
    ]
