# Generated by Django 5.1 on 2024-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobfair_use_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='event_held',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Virtual', 'Virtual')], max_length=20),
        ),
    ]
