# Generated by Django 5.1 on 2024-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobfair_event_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='event_held',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='organizer',
        ),
        migrations.AddField(
            model_name='jobfair',
            name='fair_event_held',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobfair_image/'),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='url_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
