# Generated by Django 5.1 on 2024-11-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_jobfair_event_held_remove_jobfair_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='online_link',
        ),
    ]
