# Generated by Django 5.1 on 2024-11-26 14:42

import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_jobfair_online_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='image',
            field=models.ImageField(blank=True, default='conventions.jpg', null=True, upload_to='jobfair_image/', validators=[job.models.validate_image]),
        ),
        migrations.CreateModel(
            name='JobFairRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('jobfair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobfair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
