# Generated by Django 5.1 on 2024-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_jobfair_image_jobfairregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='application_starts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
