# Generated by Django 5.1 on 2024-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobfair_application_starts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='use_company_location',
        ),
    ]
