# Generated by Django 5.1 on 2024-11-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_savejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10),
        ),
    ]
