# Generated by Django 5.1 on 2024-11-29 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_salary_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savejob',
            unique_together={('user', 'job')},
        ),
    ]
