# Generated by Django 5.1 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_savejob_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_experience',
            name='exp_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='exp_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='exp_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job_responsibilities',
            name='res_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='requiredskill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
