# Generated by Django 5.1 on 2024-11-30 11:32

import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_experience_exp_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='image',
            field=models.ImageField(blank=True, default='conventions.jpg', null=True, upload_to=job.models.jobfair_image_upload_path, validators=[job.models.validate_image]),
        ),
        migrations.AlterUniqueTogether(
            name='jobfairregistration',
            unique_together={('user', 'jobfair')},
        ),
    ]
